const KEY='ecobox-cart';
function getCart(){try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch(e){return[]}}
function setCart(c){localStorage.setItem(KEY,JSON.stringify(c));updateCartCount()}
function updateCartCount(){const n=getCart().reduce((s,x)=>s+x.qty,0);document.querySelectorAll('#cart-count').forEach(e=>e.textContent=n)}
function addToCart(name,price){let c=getCart();let x=c.find(i=>i.name===name);if(x)x.qty++;else c.push({name,price:Number(price),qty:1});setCart(c);alert(name+' added to your basket.')}
function renderCart(){const el=document.getElementById('cart-items');if(!el)return;const c=getCart();if(!c.length){el.innerHTML='<div style="padding:45px;text-align:center"><h2>Your basket is empty</h2><p class="muted">Explore the boxes and choose your first EcoBox.</p><a class="btn primary" href="shop.html">Shop boxes</a></div>';document.getElementById('cart-total').textContent='£0.00';document.getElementById('cart-grand').textContent='£0.00';return}el.innerHTML=c.map((x,i)=>`<div class="cart-row"><div class="cart-product"><div class="cart-icon">📦</div><div><b>${x.name}</b><div class="muted">£${x.price.toFixed(2)} / month × ${x.qty}</div></div></div><div><b>£${(x.price*x.qty).toFixed(2)}</b><button class="remove" onclick="removeItem(${i})">Remove</button></div></div>`).join('');const total=c.reduce((s,x)=>s+x.price*x.qty,0);document.getElementById('cart-total').textContent='£'+total.toFixed(2);document.getElementById('cart-grand').textContent='£'+total.toFixed(2)}
function removeItem(i){let c=getCart();c.splice(i,1);setCart(c);renderCart()}
function saveSignup(e){e.preventDefault();const email=document.getElementById('home-email').value;localStorage.setItem('ecobox-lead',email);document.getElementById('signup-message').textContent='Thanks — your Eco List signup has been captured for this prototype.';e.target.reset();return false}
function saveCRM(e){e.preventDefault();const lead={name:document.getElementById('first-name').value,email:document.getElementById('crm-email').value,type:document.getElementById('customer-type').value,interest:document.getElementById('interest').value,date:new Date().toISOString()};let leads=JSON.parse(localStorage.getItem('ecobox-leads')||'[]');leads.push(lead);localStorage.setItem('ecobox-leads',JSON.stringify(leads));document.getElementById('crm-message').textContent='Profile captured successfully. Thank you for joining EcoBox UK.';e.target.reset();return false}
document.addEventListener('DOMContentLoaded',()=>{updateCartCount();renderCart();document.querySelectorAll('.add-cart').forEach(b=>b.addEventListener('click',()=>addToCart(b.dataset.name,b.dataset.price)));document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.shop-item').forEach(x=>x.style.display=b.dataset.filter==='all'||x.dataset.filter===b.dataset.filter?'block':'none')}));const toggle=document.querySelector('.menu-toggle');if(toggle)toggle.addEventListener('click',()=>{const n=document.querySelector('.nav');n.style.display=n.style.display==='flex'?'none':'flex';n.style.position='absolute';n.style.top='78px';n.style.left='0';n.style.right='0';n.style.background='#fff';n.style.padding='15px 6%';n.style.flexDirection='column';n.style.alignItems='flex-start'})});